// /*
// Copyright 2025 The Exto Project Solutions, Inc.
// All rights reserved.
//
// Author: Vimalraj Arumugam
//
// This software is the confidential and proprietary product of The Exto Project Solutions, Inc.
// and is protected by copyright and trade secret law.
// Use, reproduction, and distribution of this software is strictly forbidden.
//
// For more details, please refer to the LICENSE file in the root directory of this project.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: scan_history_repo.go
//
// Generated by this command:
//
//	mockgen -source=scan_history_repo.go -destination=../mocks/mock_scan_history_repo.go -package=mocks -copyright_file=../../copy_right.txt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	app "github.com/gaeaglobal/exto/server/app"
	model "github.com/gaeaglobal/exto/server/model"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockScanHistoryRepo is a mock of ScanHistoryRepo interface.
type MockScanHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockScanHistoryRepoMockRecorder
	isgomock struct{}
}

// MockScanHistoryRepoMockRecorder is the mock recorder for MockScanHistoryRepo.
type MockScanHistoryRepoMockRecorder struct {
	mock *MockScanHistoryRepo
}

// NewMockScanHistoryRepo creates a new mock instance.
func NewMockScanHistoryRepo(ctrl *gomock.Controller) *MockScanHistoryRepo {
	mock := &MockScanHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockScanHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanHistoryRepo) EXPECT() *MockScanHistoryRepoMockRecorder {
	return m.recorder
}

// CreateScanHistory mocks base method.
func (m *MockScanHistoryRepo) CreateScanHistory(reqCtx *app.RequestContext, scanHistory *model.CreateScanHistoryRequest) (*model.ScanHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScanHistory", reqCtx, scanHistory)
	ret0, _ := ret[0].(*model.ScanHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScanHistory indicates an expected call of CreateScanHistory.
func (mr *MockScanHistoryRepoMockRecorder) CreateScanHistory(reqCtx, scanHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScanHistory", reflect.TypeOf((*MockScanHistoryRepo)(nil).CreateScanHistory), reqCtx, scanHistory)
}

// GetCollection mocks base method.
func (m *MockScanHistoryRepo) GetCollection(orgName ...string) *mongo.Collection {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range orgName {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollection", varargs...)
	ret0, _ := ret[0].(*mongo.Collection)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockScanHistoryRepoMockRecorder) GetCollection(orgName ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockScanHistoryRepo)(nil).GetCollection), orgName...)
}

// GetScanHistoryByID mocks base method.
func (m *MockScanHistoryRepo) GetScanHistoryByID(reqCtx *app.RequestContext, scanHistoryID bson.ObjectID) (*model.ScanHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanHistoryByID", reqCtx, scanHistoryID)
	ret0, _ := ret[0].(*model.ScanHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScanHistoryByID indicates an expected call of GetScanHistoryByID.
func (mr *MockScanHistoryRepoMockRecorder) GetScanHistoryByID(reqCtx, scanHistoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanHistoryByID", reflect.TypeOf((*MockScanHistoryRepo)(nil).GetScanHistoryByID), reqCtx, scanHistoryID)
}

// ListScanHistories mocks base method.
func (m *MockScanHistoryRepo) ListScanHistories(reqCtx *app.RequestContext, pageReq *app.PageRequest) (*app.PageResponse[*model.ScanHistory], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScanHistories", reqCtx, pageReq)
	ret0, _ := ret[0].(*app.PageResponse[*model.ScanHistory])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScanHistories indicates an expected call of ListScanHistories.
func (mr *MockScanHistoryRepoMockRecorder) ListScanHistories(reqCtx, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScanHistories", reflect.TypeOf((*MockScanHistoryRepo)(nil).ListScanHistories), reqCtx, pageReq)
}
