// /*
// Copyright 2025 The Exto Project Solutions, Inc.
// All rights reserved.
//
// Author: Vimalraj Arumugam
//
// This software is the confidential and proprietary product of The Exto Project Solutions, Inc.
// and is protected by copyright and trade secret law.
// Use, reproduction, and distribution of this software is strictly forbidden.
//
// For more details, please refer to the LICENSE file in the root directory of this project.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: category_repo.go
//
// Generated by this command:
//
//	mockgen -source=category_repo.go -destination=../mocks/mock_category_repo.go -package=mocks -copyright_file=../../copy_right.txt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	app "github.com/gaeaglobal/exto/server/app"
	model "github.com/gaeaglobal/exto/server/model"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryRepository is a mock of CategoryRepository interface.
type MockCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockCategoryRepositoryMockRecorder is the mock recorder for MockCategoryRepository.
type MockCategoryRepositoryMockRecorder struct {
	mock *MockCategoryRepository
}

// NewMockCategoryRepository creates a new mock instance.
func NewMockCategoryRepository(ctrl *gomock.Controller) *MockCategoryRepository {
	mock := &MockCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepository) EXPECT() *MockCategoryRepositoryMockRecorder {
	return m.recorder
}

// GetCategoryByID mocks base method.
func (m *MockCategoryRepository) GetCategoryByID(reqCtx *app.RequestContext, categoryID bson.ObjectID) (*model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", reqCtx, categoryID)
	ret0, _ := ret[0].(*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockCategoryRepositoryMockRecorder) GetCategoryByID(reqCtx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockCategoryRepository)(nil).GetCategoryByID), reqCtx, categoryID)
}

// GetCollection mocks base method.
func (m *MockCategoryRepository) GetCollection(orgName ...string) *mongo.Collection {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range orgName {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollection", varargs...)
	ret0, _ := ret[0].(*mongo.Collection)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockCategoryRepositoryMockRecorder) GetCollection(orgName ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockCategoryRepository)(nil).GetCollection), orgName...)
}

// ListCategories mocks base method.
func (m *MockCategoryRepository) ListCategories(reqCtx *app.RequestContext, pageReq *app.PageRequest) (*app.PageResponse[*model.Category], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", reqCtx, pageReq)
	ret0, _ := ret[0].(*app.PageResponse[*model.Category])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockCategoryRepositoryMockRecorder) ListCategories(reqCtx, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockCategoryRepository)(nil).ListCategories), reqCtx, pageReq)
}
