// /*
// Copyright 2025 The Exto Project Solutions, Inc.
// All rights reserved.
//
// Author: Vimalraj Arumugam
//
// This software is the confidential and proprietary product of The Exto Project Solutions, Inc.
// and is protected by copyright and trade secret law.
// Use, reproduction, and distribution of this software is strictly forbidden.
//
// For more details, please refer to the LICENSE file in the root directory of this project.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: category_data_repo.go
//
// Generated by this command:
//
//	mockgen -source=category_data_repo.go -destination=../mocks/mock_category_data_repo.go -package=mocks -copyright_file=../../copy_right.txt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	app "github.com/gaeaglobal/exto/server/app"
	model "github.com/gaeaglobal/exto/server/model"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryDataRepository is a mock of CategoryDataRepository interface.
type MockCategoryDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryDataRepositoryMockRecorder
	isgomock struct{}
}

// MockCategoryDataRepositoryMockRecorder is the mock recorder for MockCategoryDataRepository.
type MockCategoryDataRepositoryMockRecorder struct {
	mock *MockCategoryDataRepository
}

// NewMockCategoryDataRepository creates a new mock instance.
func NewMockCategoryDataRepository(ctrl *gomock.Controller) *MockCategoryDataRepository {
	mock := &MockCategoryDataRepository{ctrl: ctrl}
	mock.recorder = &MockCategoryDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryDataRepository) EXPECT() *MockCategoryDataRepositoryMockRecorder {
	return m.recorder
}

// CreateCategoryData mocks base method.
func (m *MockCategoryDataRepository) CreateCategoryData(reqCtx *app.RequestContext, categorySlug string, categoryData *model.CreateCategoryDataRequest) (*model.CategoryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryData", reqCtx, categorySlug, categoryData)
	ret0, _ := ret[0].(*model.CategoryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategoryData indicates an expected call of CreateCategoryData.
func (mr *MockCategoryDataRepositoryMockRecorder) CreateCategoryData(reqCtx, categorySlug, categoryData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryData", reflect.TypeOf((*MockCategoryDataRepository)(nil).CreateCategoryData), reqCtx, categorySlug, categoryData)
}

// GetCategoryDataByID mocks base method.
func (m *MockCategoryDataRepository) GetCategoryDataByID(reqCtx *app.RequestContext, categorySlug string, id bson.ObjectID) (*model.CategoryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryDataByID", reqCtx, categorySlug, id)
	ret0, _ := ret[0].(*model.CategoryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryDataByID indicates an expected call of GetCategoryDataByID.
func (mr *MockCategoryDataRepositoryMockRecorder) GetCategoryDataByID(reqCtx, categorySlug, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryDataByID", reflect.TypeOf((*MockCategoryDataRepository)(nil).GetCategoryDataByID), reqCtx, categorySlug, id)
}

// GetCollection mocks base method.
func (m *MockCategoryDataRepository) GetCollection(orgSlug, categorySlug string) *mongo.Collection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", orgSlug, categorySlug)
	ret0, _ := ret[0].(*mongo.Collection)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockCategoryDataRepositoryMockRecorder) GetCollection(orgSlug, categorySlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockCategoryDataRepository)(nil).GetCollection), orgSlug, categorySlug)
}

// ListCategoryData mocks base method.
func (m *MockCategoryDataRepository) ListCategoryData(reqCtx *app.RequestContext, categorySlug string, pageReq *app.PageRequest) (*app.PageResponse[*model.CategoryData], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoryData", reqCtx, categorySlug, pageReq)
	ret0, _ := ret[0].(*app.PageResponse[*model.CategoryData])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoryData indicates an expected call of ListCategoryData.
func (mr *MockCategoryDataRepositoryMockRecorder) ListCategoryData(reqCtx, categorySlug, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoryData", reflect.TypeOf((*MockCategoryDataRepository)(nil).ListCategoryData), reqCtx, categorySlug, pageReq)
}

// UpdateCategoryData mocks base method.
func (m *MockCategoryDataRepository) UpdateCategoryData(reqCtx *app.RequestContext, categorySlug string, id bson.ObjectID, updateMetaData *model.UpdateCategoryDataRequest) (*model.CategoryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategoryData", reqCtx, categorySlug, id, updateMetaData)
	ret0, _ := ret[0].(*model.CategoryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategoryData indicates an expected call of UpdateCategoryData.
func (mr *MockCategoryDataRepositoryMockRecorder) UpdateCategoryData(reqCtx, categorySlug, id, updateMetaData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategoryData", reflect.TypeOf((*MockCategoryDataRepository)(nil).UpdateCategoryData), reqCtx, categorySlug, id, updateMetaData)
}
