// /*
// Copyright 2025 The Exto Project Solutions, Inc.
// All rights reserved.
//
// Author: Vimalraj Arumugam
//
// This software is the confidential and proprietary product of The Exto Project Solutions, Inc.
// and is protected by copyright and trade secret law.
// Use, reproduction, and distribution of this software is strictly forbidden.
//
// For more details, please refer to the LICENSE file in the root directory of this project.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: organization_repo.go
//
// Generated by this command:
//
//	mockgen -source=organization_repo.go -destination=../mocks/mock_organization_repo.go -package=mocks -copyright_file=../../copy_right.txt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	app "github.com/gaeaglobal/exto/server/app"
	model "github.com/gaeaglobal/exto/server/model"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationRepo is a mock of OrganizationRepo interface.
type MockOrganizationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepoMockRecorder
	isgomock struct{}
}

// MockOrganizationRepoMockRecorder is the mock recorder for MockOrganizationRepo.
type MockOrganizationRepoMockRecorder struct {
	mock *MockOrganizationRepo
}

// NewMockOrganizationRepo creates a new mock instance.
func NewMockOrganizationRepo(ctrl *gomock.Controller) *MockOrganizationRepo {
	mock := &MockOrganizationRepo{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepo) EXPECT() *MockOrganizationRepoMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockOrganizationRepo) CreateOrganization(reqCtx *app.RequestContext, org *model.CreateOrganization, createdByIdentity bson.ObjectID) (*model.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", reqCtx, org, createdByIdentity)
	ret0, _ := ret[0].(*model.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockOrganizationRepoMockRecorder) CreateOrganization(reqCtx, org, createdByIdentity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockOrganizationRepo)(nil).CreateOrganization), reqCtx, org, createdByIdentity)
}

// DeleteOrganizationByOwner mocks base method.
func (m *MockOrganizationRepo) DeleteOrganizationByOwner(reqCtx *app.RequestContext) ([]*model.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganizationByOwner", reqCtx)
	ret0, _ := ret[0].([]*model.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrganizationByOwner indicates an expected call of DeleteOrganizationByOwner.
func (mr *MockOrganizationRepoMockRecorder) DeleteOrganizationByOwner(reqCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganizationByOwner", reflect.TypeOf((*MockOrganizationRepo)(nil).DeleteOrganizationByOwner), reqCtx)
}

// GenerateNextScanCode mocks base method.
func (m *MockOrganizationRepo) GenerateNextScanCode(reqCtx *app.RequestContext) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNextScanCode", reqCtx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateNextScanCode indicates an expected call of GenerateNextScanCode.
func (mr *MockOrganizationRepoMockRecorder) GenerateNextScanCode(reqCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNextScanCode", reflect.TypeOf((*MockOrganizationRepo)(nil).GenerateNextScanCode), reqCtx)
}

// GetCollection mocks base method.
func (m *MockOrganizationRepo) GetCollection(orgName ...string) *mongo.Collection {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range orgName {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollection", varargs...)
	ret0, _ := ret[0].(*mongo.Collection)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockOrganizationRepoMockRecorder) GetCollection(orgName ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockOrganizationRepo)(nil).GetCollection), orgName...)
}

// GetOrganizationByID mocks base method.
func (m *MockOrganizationRepo) GetOrganizationByID(reqCtx *app.RequestContext, id bson.ObjectID) (*model.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByID", reqCtx, id)
	ret0, _ := ret[0].(*model.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByID indicates an expected call of GetOrganizationByID.
func (mr *MockOrganizationRepoMockRecorder) GetOrganizationByID(reqCtx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByID", reflect.TypeOf((*MockOrganizationRepo)(nil).GetOrganizationByID), reqCtx, id)
}

// GetOrganizationCount mocks base method.
func (m *MockOrganizationRepo) GetOrganizationCount(reqCtx *app.RequestContext) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationCount", reqCtx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationCount indicates an expected call of GetOrganizationCount.
func (mr *MockOrganizationRepoMockRecorder) GetOrganizationCount(reqCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationCount", reflect.TypeOf((*MockOrganizationRepo)(nil).GetOrganizationCount), reqCtx)
}

// GetOrganizations mocks base method.
func (m *MockOrganizationRepo) GetOrganizations(reqCtx *app.RequestContext, filter bson.M) ([]*model.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizations", reqCtx, filter)
	ret0, _ := ret[0].([]*model.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizations indicates an expected call of GetOrganizations.
func (mr *MockOrganizationRepoMockRecorder) GetOrganizations(reqCtx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizations", reflect.TypeOf((*MockOrganizationRepo)(nil).GetOrganizations), reqCtx, filter)
}

// IsOrganizationExists mocks base method.
func (m *MockOrganizationRepo) IsOrganizationExists(reqCtx *app.RequestContext, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOrganizationExists", reqCtx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOrganizationExists indicates an expected call of IsOrganizationExists.
func (mr *MockOrganizationRepoMockRecorder) IsOrganizationExists(reqCtx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOrganizationExists", reflect.TypeOf((*MockOrganizationRepo)(nil).IsOrganizationExists), reqCtx, name)
}

// ListOrganizations mocks base method.
func (m *MockOrganizationRepo) ListOrganizations(reqCtx *app.RequestContext, pageReq *app.PageRequest) (*app.PageResponse[*model.Organization], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", reqCtx, pageReq)
	ret0, _ := ret[0].(*app.PageResponse[*model.Organization])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockOrganizationRepoMockRecorder) ListOrganizations(reqCtx, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockOrganizationRepo)(nil).ListOrganizations), reqCtx, pageReq)
}

// UpdateOrganization mocks base method.
func (m *MockOrganizationRepo) UpdateOrganization(reqCtx *app.RequestContext, id bson.ObjectID, org *model.UpdateOrganization) (*model.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", reqCtx, id, org)
	ret0, _ := ret[0].(*model.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockOrganizationRepoMockRecorder) UpdateOrganization(reqCtx, id, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockOrganizationRepo)(nil).UpdateOrganization), reqCtx, id, org)
}
