// /*
// Copyright 2025 The Exto Project Solutions, Inc.
// All rights reserved.
//
// Author: Vimalraj Arumugam
//
// This software is the confidential and proprietary product of The Exto Project Solutions, Inc.
// and is protected by copyright and trade secret law.
// Use, reproduction, and distribution of this software is strictly forbidden.
//
// For more details, please refer to the LICENSE file in the root directory of this project.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: identity_repo.go
//
// Generated by this command:
//
//	mockgen -source=identity_repo.go -destination=../mocks/mock_identity_repo.go -package=mocks -copyright_file=../../copy_right.txt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	app "github.com/gaeaglobal/exto/server/app"
	model "github.com/gaeaglobal/exto/server/model"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityRepo is a mock of IdentityRepo interface.
type MockIdentityRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityRepoMockRecorder
	isgomock struct{}
}

// MockIdentityRepoMockRecorder is the mock recorder for MockIdentityRepo.
type MockIdentityRepoMockRecorder struct {
	mock *MockIdentityRepo
}

// NewMockIdentityRepo creates a new mock instance.
func NewMockIdentityRepo(ctrl *gomock.Controller) *MockIdentityRepo {
	mock := &MockIdentityRepo{ctrl: ctrl}
	mock.recorder = &MockIdentityRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityRepo) EXPECT() *MockIdentityRepoMockRecorder {
	return m.recorder
}

// CreateIdentity mocks base method.
func (m *MockIdentityRepo) CreateIdentity(reqCtx *app.RequestContext, identity *model.CreateIdentity) (*model.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentity", reqCtx, identity)
	ret0, _ := ret[0].(*model.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIdentity indicates an expected call of CreateIdentity.
func (mr *MockIdentityRepoMockRecorder) CreateIdentity(reqCtx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentity", reflect.TypeOf((*MockIdentityRepo)(nil).CreateIdentity), reqCtx, identity)
}

// DeleteIdentity mocks base method.
func (m *MockIdentityRepo) DeleteIdentity(reqCtx *app.RequestContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdentity", reqCtx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdentity indicates an expected call of DeleteIdentity.
func (mr *MockIdentityRepoMockRecorder) DeleteIdentity(reqCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdentity", reflect.TypeOf((*MockIdentityRepo)(nil).DeleteIdentity), reqCtx)
}

// GetCollection mocks base method.
func (m *MockIdentityRepo) GetCollection(orgName ...string) *mongo.Collection {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range orgName {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollection", varargs...)
	ret0, _ := ret[0].(*mongo.Collection)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockIdentityRepoMockRecorder) GetCollection(orgName ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockIdentityRepo)(nil).GetCollection), orgName...)
}

// GetIdentityByEmail mocks base method.
func (m *MockIdentityRepo) GetIdentityByEmail(reqCtx *app.RequestContext, email string) (*model.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentityByEmail", reqCtx, email)
	ret0, _ := ret[0].(*model.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentityByEmail indicates an expected call of GetIdentityByEmail.
func (mr *MockIdentityRepoMockRecorder) GetIdentityByEmail(reqCtx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentityByEmail", reflect.TypeOf((*MockIdentityRepo)(nil).GetIdentityByEmail), reqCtx, email)
}

// IsIdentityExists mocks base method.
func (m *MockIdentityRepo) IsIdentityExists(reqCtx *app.RequestContext, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsIdentityExists", reqCtx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsIdentityExists indicates an expected call of IsIdentityExists.
func (mr *MockIdentityRepoMockRecorder) IsIdentityExists(reqCtx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsIdentityExists", reflect.TypeOf((*MockIdentityRepo)(nil).IsIdentityExists), reqCtx, email)
}

// UpdateIdentity mocks base method.
func (m *MockIdentityRepo) UpdateIdentity(reqCtx *app.RequestContext, id bson.ObjectID, identity *model.UpdateIdentity) (*model.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIdentity", reqCtx, id, identity)
	ret0, _ := ret[0].(*model.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIdentity indicates an expected call of UpdateIdentity.
func (mr *MockIdentityRepoMockRecorder) UpdateIdentity(reqCtx, id, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIdentity", reflect.TypeOf((*MockIdentityRepo)(nil).UpdateIdentity), reqCtx, id, identity)
}
