// /*
// Copyright 2025 The Exto Project Solutions, Inc.
// All rights reserved.
//
// Author: Vimalraj Arumugam
//
// This software is the confidential and proprietary product of The Exto Project Solutions, Inc.
// and is protected by copyright and trade secret law.
// Use, reproduction, and distribution of this software is strictly forbidden.
//
// For more details, please refer to the LICENSE file in the root directory of this project.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: user_repo.go
//
// Generated by this command:
//
//	mockgen -source=user_repo.go -destination=../mocks/mock_user_repo.go -package=mocks -copyright_file=../../copy_right.txt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	app "github.com/gaeaglobal/exto/server/app"
	model "github.com/gaeaglobal/exto/server/model"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepo) CreateUser(reqCtx *app.RequestContext, createdByIdentityId bson.ObjectID, user *model.CreateUser) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", reqCtx, createdByIdentityId, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepoMockRecorder) CreateUser(reqCtx, createdByIdentityId, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepo)(nil).CreateUser), reqCtx, createdByIdentityId, user)
}

// DeleteUserByOrgIDs mocks base method.
func (m *MockUserRepo) DeleteUserByOrgIDs(reqCtx *app.RequestContext, orgIDs []bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByOrgIDs", reqCtx, orgIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByOrgIDs indicates an expected call of DeleteUserByOrgIDs.
func (mr *MockUserRepoMockRecorder) DeleteUserByOrgIDs(reqCtx, orgIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByOrgIDs", reflect.TypeOf((*MockUserRepo)(nil).DeleteUserByOrgIDs), reqCtx, orgIDs)
}

// GetCollection mocks base method.
func (m *MockUserRepo) GetCollection(orgName ...string) *mongo.Collection {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range orgName {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollection", varargs...)
	ret0, _ := ret[0].(*mongo.Collection)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockUserRepoMockRecorder) GetCollection(orgName ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockUserRepo)(nil).GetCollection), orgName...)
}

// GetUserByID mocks base method.
func (m *MockUserRepo) GetUserByID(reqCtx *app.RequestContext, id bson.ObjectID) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", reqCtx, id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepoMockRecorder) GetUserByID(reqCtx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserByID), reqCtx, id)
}

// GetUsersByOrgID mocks base method.
func (m *MockUserRepo) GetUsersByOrgID(reqCtx *app.RequestContext, orgID bson.ObjectID, pageReq *app.PageRequest) (*app.PageResponse[*model.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByOrgID", reqCtx, orgID, pageReq)
	ret0, _ := ret[0].(*app.PageResponse[*model.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByOrgID indicates an expected call of GetUsersByOrgID.
func (mr *MockUserRepoMockRecorder) GetUsersByOrgID(reqCtx, orgID, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByOrgID", reflect.TypeOf((*MockUserRepo)(nil).GetUsersByOrgID), reqCtx, orgID, pageReq)
}

// IsUserExists mocks base method.
func (m *MockUserRepo) IsUserExists(reqCtx *app.RequestContext, orgID bson.ObjectID, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserExists", reqCtx, orgID, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserExists indicates an expected call of IsUserExists.
func (mr *MockUserRepoMockRecorder) IsUserExists(reqCtx, orgID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserExists", reflect.TypeOf((*MockUserRepo)(nil).IsUserExists), reqCtx, orgID, email)
}

// UpdateUser mocks base method.
func (m *MockUserRepo) UpdateUser(reqCtx *app.RequestContext, id bson.ObjectID, user *model.UpdateUser) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", reqCtx, id, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepoMockRecorder) UpdateUser(reqCtx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepo)(nil).UpdateUser), reqCtx, id, user)
}
