// /*
// Copyright 2025 The Exto Project Solutions, Inc.
// All rights reserved.
//
// Author: Vimalraj Arumugam
//
// This software is the confidential and proprietary product of The Exto Project Solutions, Inc.
// and is protected by copyright and trade secret law.
// Use, reproduction, and distribution of this software is strictly forbidden.
//
// For more details, please refer to the LICENSE file in the root directory of this project.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: app/db.go
//
// Generated by this command:
//
//	mockgen -source=app/db.go -destination=mocks/mock_app_db.go -package=mocks -copyright_file=../copy_right.txt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/gaeaglobal/exto/server/model"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockIAppDB is a mock of IAppDB interface.
type MockIAppDB struct {
	ctrl     *gomock.Controller
	recorder *MockIAppDBMockRecorder
	isgomock struct{}
}

// MockIAppDBMockRecorder is the mock recorder for MockIAppDB.
type MockIAppDBMockRecorder struct {
	mock *MockIAppDB
}

// NewMockIAppDB creates a new mock instance.
func NewMockIAppDB(ctrl *gomock.Controller) *MockIAppDB {
	mock := &MockIAppDB{ctrl: ctrl}
	mock.recorder = &MockIAppDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAppDB) EXPECT() *MockIAppDBMockRecorder {
	return m.recorder
}

// GetCoreDatabase mocks base method.
func (m *MockIAppDB) GetCoreDatabase() *mongo.Database {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoreDatabase")
	ret0, _ := ret[0].(*mongo.Database)
	return ret0
}

// GetCoreDatabase indicates an expected call of GetCoreDatabase.
func (mr *MockIAppDBMockRecorder) GetCoreDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoreDatabase", reflect.TypeOf((*MockIAppDB)(nil).GetCoreDatabase))
}

// GetOrgDatabase mocks base method.
func (m *MockIAppDB) GetOrgDatabase(orgName string) *mongo.Database {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgDatabase", orgName)
	ret0, _ := ret[0].(*mongo.Database)
	return ret0
}

// GetOrgDatabase indicates an expected call of GetOrgDatabase.
func (mr *MockIAppDBMockRecorder) GetOrgDatabase(orgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgDatabase", reflect.TypeOf((*MockIAppDB)(nil).GetOrgDatabase), orgName)
}

// GetUserByEmail mocks base method.
func (m *MockIAppDB) GetUserByEmail(email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockIAppDBMockRecorder) GetUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockIAppDB)(nil).GetUserByEmail), email)
}
