// /*
// Copyright 2025 The Exto Project Solutions, Inc.
// All rights reserved.
//
// Author: Vimalraj Arumugam
//
// This software is the confidential and proprietary product of The Exto Project Solutions, Inc.
// and is protected by copyright and trade secret law.
// Use, reproduction, and distribution of this software is strictly forbidden.
//
// For more details, please refer to the LICENSE file in the root directory of this project.
// */

// Code generated by MockGen. DO NOT EDIT.
// Source: format_repo.go
//
// Generated by this command:
//
//	mockgen -source=format_repo.go -destination=../mocks/mock_format_repo.go -package=mocks -copyright_file=../../copy_right.txt
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	app "github.com/gaeaglobal/exto/server/app"
	model "github.com/gaeaglobal/exto/server/model"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockFormatRepository is a mock of FormatRepository interface.
type MockFormatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFormatRepositoryMockRecorder
	isgomock struct{}
}

// MockFormatRepositoryMockRecorder is the mock recorder for MockFormatRepository.
type MockFormatRepositoryMockRecorder struct {
	mock *MockFormatRepository
}

// NewMockFormatRepository creates a new mock instance.
func NewMockFormatRepository(ctrl *gomock.Controller) *MockFormatRepository {
	mock := &MockFormatRepository{ctrl: ctrl}
	mock.recorder = &MockFormatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormatRepository) EXPECT() *MockFormatRepositoryMockRecorder {
	return m.recorder
}

// GetCollection mocks base method.
func (m *MockFormatRepository) GetCollection(orgName ...string) *mongo.Collection {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range orgName {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollection", varargs...)
	ret0, _ := ret[0].(*mongo.Collection)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockFormatRepositoryMockRecorder) GetCollection(orgName ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockFormatRepository)(nil).GetCollection), orgName...)
}

// GetFormatsByCategoryID mocks base method.
func (m *MockFormatRepository) GetFormatsByCategoryID(reqCtx *app.RequestContext, categoryID bson.ObjectID) ([]model.Format, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormatsByCategoryID", reqCtx, categoryID)
	ret0, _ := ret[0].([]model.Format)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormatsByCategoryID indicates an expected call of GetFormatsByCategoryID.
func (mr *MockFormatRepositoryMockRecorder) GetFormatsByCategoryID(reqCtx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormatsByCategoryID", reflect.TypeOf((*MockFormatRepository)(nil).GetFormatsByCategoryID), reqCtx, categoryID)
}
